### PR TITLE
hw-3

### PR DESCRIPTION
**Pull request by ihoryan**
Service is done.
FE getting data from backend
Additional scope:
 - Async/await is used in lambda functions
- ES6 modules are used for product-service implementation
- Webpack is configured for product-service
- Lambda handlers (getProductsList, getProductsById) code is written not in 1 single module (file) and separated in codebase.
- Main error scenarious are handled by API ("Product not found" error, try catch blocks are used in lambda handlers).

Link to api: 
https://nvm9mjawcl.execute-api.eu-west-1.amazonaws.com/dev/products/
https://nvm9mjawcl.execute-api.eu-west-1.amazonaws.com/dev/products/7567ec4b-b10c-48c5-9345-fc73c48a80aa

FE PR: https://github.com/ihoryan/nodejs-aws-fe/pull/2

Swagger:
{
  "swagger": "2.0",
  "info": {
    "version": "2020-10-31T10:06:02Z",
    "title": "dev-product-api"
  },
  "host": "nvm9mjawcl.execute-api.eu-west-1.amazonaws.com",
  "basePath": "/dev",
  "schemes": [
    "https"
  ],
  "paths": {
    "/products": {
      "get": {
        "responses": {
          "message": "success",
          "data": [
              {
                  "count": 4,
                  "description": "Short Product Description1",
                  "id": "7567ec4b-b10c-48c5-9345-fc73c48a80aa",
                  "price": 2.4,
                  "title": "ProductOne"
              },
              {
                  "count": 6,
                  "description": "Short Product Description3",
                  "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a0",
                  "price": 10,
                  "title": "ProductNew"
              },
              {
                  "count": 7,
                  "description": "Short Product Description2",
                  "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a2",
                  "price": 23,
                  "title": "ProductTop"
              },
              {
                  "count": 12,
                  "description": "Short Product Description7",
                  "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a1",
                  "price": 15,
                  "title": "ProductTitle"
              },
              {
                  "count": 7,
                  "description": "Short Product Description2",
                  "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a2",
                  "price": 23,
                  "title": "Product"
              },
              {
                  "count": 8,
                  "description": "Short Product Description4",
                  "id": "7567ec4b-b10c-48c5-9345-fc73348a80a1",
                  "price": 15,
                  "title": "ProductTest"
              },
              {
                  "count": 2,
                  "description": "Short Product Descriptio1",
                  "id": "7567ec4b-b10c-48c5-9445-fc73c48a80a2",
                  "price": 23,
                  "title": "Product2"
              },
              {
                  "count": 3,
                  "description": "Short Product Description7",
                  "id": "7567ec4b-b10c-45c5-9345-fc73c48a80a1",
                  "price": 15,
                  "title": "ProductName"
              }
          ]
      }
      },
      "options": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "headers": {
              "Access-Control-Allow-Origin": {
                "type": "string"
              },
              "Access-Control-Allow-Methods": {
                "type": "string"
              },
              "Access-Control-Allow-Headers": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "responses": {
          "message": "success",
          "data": {
              "count": 4,
              "description": "Short Product Description1",
              "id": "7567ec4b-b10c-48c5-9345-fc73c48a80aa",
              "price": 2.4,
              "title": "ProductOne"
          }
      }
      },
      "options": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "headers": {
              "Access-Control-Allow-Origin": {
                "type": "string"
              },
              "Access-Control-Allow-Methods": {
                "type": "string"
              },
              "Access-Control-Allow-Headers": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}

### CODE REVIEW

**Review by NurbekAman — APPROVED** [review]

**Comment by numatay** [comment]
@ihoryan Do you have a link for the uploaded version of your front end?

**Review by numatay — COMMENTED** [review]
Are you considering adding unit tests for the functions?

**Comment by ihoryan** [comment]
> @ihoryan Do you have a link for the uploaded version of your front end?

Sure
https://d1086iv4j5u5x9.cloudfront.net/

**Comment by ihoryan** [comment]
> Are you considering adding unit tests for the functions?

No, That's final version😊

**Comment by numatay** [comment]
Unfortunately, this page doesn't work https://d1086iv4j5u5x9.cloudfront.net/admin/products
Would you mind fixing that?

**Comment by ihoryan** [comment]
> Unfortunately, this page doesn't work https://d1086iv4j5u5x9.cloudfront.net/admin/products
> Would you mind fixing that?

 As I understood this home work, I just should implement 2 endpoints getProduct and getProductById and retrieve product list from backend with minimal changes in fe project.

**Pull request merged**
